stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: diagon/peer1
      pushRemote: true
      registry: 127.0.0.1:34533
timeout: 60
